"""Scorecard from the latest full run of every model and test: python -m simlab.scorecard -> docs/scorecard.md

Reads runs/scorecard.jsonl (metrics), runs/<test>__<model>.jsonl (per-item rows, for bias checks) and
runs/spend.jsonl (cost per call). Rows from --limit runs and failed runs are ignored.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy.stats import spearmanr

from .core import RUNS

DOCS = RUNS.parent / "docs"
SCOPES = ["national", "Ohio", "North Carolina", "Texas"]
ORDER = ["jev", "jev1", "kev", "kev1", "glm", "glm1", "mimo", "mimo1", "deepseek", "deepseek1", "luna", "luna1",
         "regression"]


def latest() -> dict:
    best = {}
    for line in (RUNS / "scorecard.jsonl").read_text().splitlines():
        r = json.loads(line)
        if r.get("limit") or "error" in r:
            continue
        k = (r["test"], r["model"])
        if k not in best or r["ts"] >= best[k]["ts"]:
            best[k] = r
    return best


def cost_per_1000() -> dict:
    """USD per 1,000 calls per model, from ledger entries tagged '<test>:<model>' (single-order variants are
    cached subsets, so they get the base model's price)."""
    usd, n = defaultdict(float), defaultdict(int)
    for line in (RUNS / "spend.jsonl").read_text().splitlines():
        e = json.loads(line)
        if ":" in e["tag"]:
            m = e["tag"].split(":", 1)[1]
            usd[m] += e["usd"]
            n[m] += 1
    return {m: 1000 * usd[m] / n[m] for m in n if n[m]}


def fidelity_bias(target: str, scope: str, model: str, key: str) -> float | None:
    p = RUNS / f"fidelity_{target}_{scope}__{model}.jsonl"
    if not p.exists():
        return None
    rows = [json.loads(l) for l in p.read_text().splitlines()]
    w = np.array([r["n"] for r in rows])
    d = np.array([r["pred"].get(key, 0) - r["target"].get(key, 0) for r in rows])
    return float(np.average(d, weights=w))


def events_ci(model: str, n: int = 2000, seed: int = 0) -> str:
    """90% bootstrap interval (resampling events) for the rank correlation: 19 events is a small sample."""
    p = RUNS / f"events__{model}.jsonl"
    if not p.exists():
        return "–"
    rows = [json.loads(l) for l in p.read_text().splitlines()]
    x, y = np.array([r["pred"]["all"] for r in rows]), np.array([r["measured"] for r in rows], float)
    rng, stats = np.random.default_rng(seed), []
    for _ in range(n):
        i = rng.integers(0, len(x), len(x))
        if len(set(x[i])) > 1 and len(set(y[i])) > 1:
            stats.append(spearmanr(x[i], y[i])[0])
    lo, hi = np.percentile(stats, [5, 95])
    return f"{lo:.2f} to {hi:.2f}"


def f(x, nd=2, pct=False):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "–"
    return f"{100 * x:+.0f}" if pct else f"{x:.{nd}f}"


def table(head: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    return "\n".join(out + ["| " + " | ".join(r) + " |" for r in rows])


def build() -> str:
    ev = json.loads((Path(__file__).parent / "events.json").read_text())
    y, w = np.array([e["shift_toward_D"] for e in ev], float), np.array([e["weight"] for e in ev])
    zero_rmse = float(np.sqrt(np.average(y ** 2, weights=w)))  # always predicting "no change"
    s, cost = latest(), cost_per_1000()
    models = [m for m in ORDER if any(k[1] == m for k in s)]
    base = lambda m: m[:-1] if m.endswith("1") else m

    def per_decision(m):  # a 5-level scale question costs 2 calls when averaged over both directions, 1 otherwise
        c = cost.get(base(m))
        return None if c is None else c * (1 if m.endswith("1") else 2)

    parts = ["# Test bench scorecard", "",
             "Generated by `python -m simlab.scorecard` from the latest full run of each model. Models ending in 1 "
             "ask each question in one option order only (the others average scales over both directions and "
             "choices over 3 orders). `regression` is the plain statistical baseline (fidelity only).", ""]

    rows = []
    for m in models:
        r = s.get(("null", m))
        if r:
            rows.append([m, f(r["support_p_no_change"]), f(r["turnout_p_no_change"]),
                         f(r["support_mean_abs_shift"], 3), f(r["turnout_mean_abs_shift"], 3)])
    parts += ["## Null: irrelevant news should change nothing (pass: P(no change) ≥ 0.90)", "",
              table(["model", "P(no change), support", "P(no change), turnout", "avg |shift|, support",
                     "avg |shift|, turnout"], rows), ""]

    rows = []
    for m in models:
        r = s.get(("mirror", m))
        if r:
            rel = r["mean_asymmetry"] / r["mean_abs_reaction"] if r["mean_abs_reaction"] else None
            rows.append([m, f(r["flip_corr"]), f(r["sign_flip_rate"]), f(r["mean_asymmetry"], 3),
                         f(rel, pct=True) + "%" if rel is not None else "–", f(r["mean_abs_reaction"])])
    parts += ["## Mirror: same story, parties swapped (reaction should flip; no built-in lean)", "",
              "Lean = average of the two reactions (+ = toward Democrats), also shown as a share of the model's "
              "typical reaction size. Scale is −2..+2 per person.", "",
              table(["model", "flip correlation", "sign flips", "lean", "lean / reaction size",
                     "avg reaction size"], rows), ""]

    rows = []
    for m in models:
        r = s.get(("events", m))
        if r:
            rows.append([m, f(r["spearman"]), events_ci(m), f(r["sign_accuracy_nonnull"]),
                         f(r["null_events_mean_abs_pred"], 3), f(r["scale_points_per_unit"], 1),
                         f(r["rmse_after_scaling"]), f(r["party_corr"])])
    parts += ["## Events: 19 real events 2012–2026 with measured shifts", "",
              f"Always predicting \"no change\" gives an error of {zero_rmse:.2f} points. Points per unit = real "
              "shift per unit of the model's scale (fitted); error is after that scaling. Most events predate the "
              "models' training cutoffs, so a model may partly remember how they played out.", "",
              table(["model", "rank correlation", "90% interval", "right direction (13 non-null)",
                     "avg |pred| on 6 null events", "points per unit", "error after scaling (pts)",
                     "party correlation"], rows), ""]

    for target, key, label in (("vote24", "harris", "2024 vote (validated voters)"),
                               ("turnout", "true", "turnout (Census CPS 2024, each state matched to its official turnout)")):
        rows = []
        for m in models:
            rs = [s.get((f"fidelity_{target}_{sc}", m)) for sc in SCOPES]
            if not any(rs):
                continue
            bias = fidelity_bias(target, "national", m, key)
            rows.append([m] + [f(r["tvd_weighted"], 3) if r else "–" for r in rs]
                        + [f(rs[0][f"corr_{key}"]) if rs[0] else "–",
                           (f(bias, pct=True) + " pts") if bias is not None else "–"])
        what = "Harris share" if key == "harris" else "turnout"
        parts += [f"## Fidelity: {label}", "",
                  "Weighted total variation distance between predicted and real shares by demographic cell (lower is "
                  f"better). Bias = average predicted minus real {what}, national cells.", "",
                  table(["model", *[f"TVD {sc}" for sc in SCOPES], "correlation (national)", f"bias in {what}"],
                        rows), ""]

    rows = []
    for m in models:
        if m == "regression":
            continue
        c, d = cost.get(base(m)), per_decision(m)
        rows.append([m, f(c, 4), f(d, 4), f(d * 300 if d is not None else None, 2)])
    parts += ["## Cost", "",
              "From the spend ledger, with today's short prompts (~200–350 tokens). A decision = one 5-level question "
              "for one persona and one story. Monthly figure = 300,000 decisions (about 10,000 a day, the full-scale "
              "reaction volume in docs/infrastructure.md).", "",
              table(["model", "$ per 1,000 calls", "$ per 1,000 decisions", "$ per month at 300k decisions"],
                    rows), ""]
    return "\n".join(parts)


if __name__ == "__main__":
    md = build()
    (DOCS / "scorecard.md").write_text(md, encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # Windows consoles default to cp1252
    print(md)
